version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: nest_pg
    restart: always
    environment:
      POSTGRES_USER: abhay
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: devflow_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
